package workspace

import (
	"sort"
	"strings"

	"github.com/takealook97/vat/internal/fsx"
	"github.com/takealook97/vat/internal/manifest"
)

// Managed .gitignore region markers. vat owns only what sits between them; a
// user's own ignore rules above and below are preserved exactly.
const (
	ignoreBegin = "# vat:begin managed — regenerated by `vat repo` and `vat lint --fix`"
	ignoreEnd   = "# vat:end managed"
)

// GitignorePath returns the workspace's own .gitignore.
func (w *Workspace) GitignorePath() string { return w.Path(".gitignore") }

// RenderGitignoreRegion returns the managed block for a manifest. Each governed
// repository is excluded from the workspace's own history because each one is
// an independent git repository that owns its commits, and a workspace commit
// that swallowed a nested tree would silently duplicate them.
func RenderGitignoreRegion(m manifest.Manifest) string {
	dirs := make([]string, 0, len(m.Repos))
	for _, repo := range m.Repos {
		dirs = append(dirs, repo.Dir()+"/")
	}
	sort.Strings(dirs)

	var b strings.Builder
	b.WriteString(ignoreBegin)
	b.WriteString("\n")
	// A workspace that governs nothing is what adopting the harness for a single
	// repository produces, and this text is committed into that repository.
	// Announcing a list and printing none reads as a defect in the generated
	// file rather than as the state it is describing.
	if len(dirs) > 0 {
		b.WriteString("# Every repository below is an independent git repository.\n")
		b.WriteString("# The workspace tracks the manifest that governs them, never their trees.\n")
		for _, dir := range dirs {
			b.WriteString(dir)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	b.WriteString("# vat's own derived, regenerable local state.\n")
	b.WriteString(".vat/\n")
	b.WriteString(ignoreEnd)
	return b.String()
}

// CountGitignoreRegions reports how many managed regions the content holds.
// vat replaces the first and never looks past it, so a second one is a frozen
// copy of an old roster — and because the last matching pattern in a
// .gitignore decides, it is the copy that wins.
func CountGitignoreRegions(content string) int {
	count, rest := 0, content
	for {
		beginAt := strings.Index(rest, ignoreBegin)
		if beginAt < 0 {
			return count
		}
		endAt := strings.Index(rest[beginAt:], ignoreEnd)
		if endAt < 0 {
			return count
		}
		count++
		rest = rest[beginAt+endAt+len(ignoreEnd):]
	}
}

// ApplyGitignoreRegion returns existing .gitignore content with the managed
// region replaced, appending the region when it is absent. It never mutates
// the caller's string.
func ApplyGitignoreRegion(existing, region string) string {
	beginAt := strings.Index(existing, ignoreBegin)
	endAt := strings.Index(existing, ignoreEnd)
	if beginAt >= 0 && endAt > beginAt {
		tail := existing[endAt+len(ignoreEnd):]
		return existing[:beginAt] + region + tail
	}
	trimmed := strings.TrimRight(existing, "\n")
	if trimmed == "" {
		return region + "\n"
	}
	return trimmed + "\n\n" + region + "\n"
}

// GitignoreRegionOf extracts the managed region from .gitignore content, and
// reports whether one was present.
func GitignoreRegionOf(existing string) (string, bool) {
	beginAt := strings.Index(existing, ignoreBegin)
	endAt := strings.Index(existing, ignoreEnd)
	if beginAt < 0 || endAt <= beginAt {
		return "", false
	}
	return existing[beginAt : endAt+len(ignoreEnd)], true
}

// SyncGitignore rewrites the managed region to match the manifest and reports
// whether the file changed. This is what closes the failure mode where a
// repository is added to the manifest but forgotten in .gitignore, so the next
// workspace commit absorbs the whole clone.
func (w *Workspace) SyncGitignore(m manifest.Manifest) (bool, error) {
	path := w.GitignorePath()
	current, _, err := fsx.ReadFileIfExists(path)
	if err != nil {
		return false, err
	}
	next := ApplyGitignoreRegion(string(current), RenderGitignoreRegion(m))
	// Compared on content: under the default core.autocrlf on Windows this file
	// comes back with CRLF, and an exact match had every command that touches
	// the manifest rewrite it and report ".gitignore updated".
	if fsx.NormaliseNewlines(next) == fsx.NormaliseNewlines(string(current)) {
		return false, nil
	}
	if err := fsx.WriteFileAtomic(path, []byte(next), fsx.DefaultFileMode); err != nil {
		return false, err
	}
	return true, nil
}

// GitignoreDrift returns the repositories the manifest governs that the managed
// .gitignore region does not exclude.
func (w *Workspace) GitignoreDrift(m manifest.Manifest) ([]string, error) {
	current, _, err := fsx.ReadFileIfExists(w.GitignorePath())
	if err != nil {
		return nil, err
	}
	region, ok := GitignoreRegionOf(string(current))
	if !ok {
		// No managed region at all: fall back to the whole file, so a
		// hand-maintained .gitignore that happens to be correct is not
		// reported as drift.
		region = string(current)
	}
	lines := map[string]bool{}
	for _, line := range strings.Split(region, "\n") {
		lines[strings.TrimSpace(line)] = true
	}
	var missing []string
	for _, repo := range m.Repos {
		dir := repo.Dir()
		if lines[dir+"/"] || lines[dir] || lines["/"+dir+"/"] {
			continue
		}
		missing = append(missing, dir)
	}
	sort.Strings(missing)
	return missing, nil
}
