package lint

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/takealook97/vat/internal/fsx"
	"github.com/takealook97/vat/internal/harness"
	"github.com/takealook97/vat/internal/workspace"
)

// The rules that judge generated agent contracts and the definitions behind
// them. Split from lint.go because they are the largest cohesive group in the
// package and the file they were in had grown past the point where the rest of
// it could be read in one sitting.

// workspaceContract is the file every harness rule below reports against.
const workspaceContract = "AGENTS.md"

func checkHarness(ws *workspace.Workspace) ([]Finding, error) {
	var findings []Finding

	rootPath := ws.Path(workspaceContract)
	content, exists, err := fsx.ReadFileIfExists(rootPath)
	if err != nil {
		return nil, err
	}
	region := harness.RenderWorkspace(ws.Manifest)
	switch {
	case !exists:
		findings = append(findings, Finding{
			Rule: "harness/workspace-missing", Severity: SeverityError, Subject: workspaceContract,
			Message: "the workspace has no agent contract",
			Fix:     fixHarness, Fixable: true,
		})
	case harness.CountRegions(string(content)) > 1:
		// Reported before drift, because drift is about the region vat
		// maintains and this is about the one it does not. Not repairable:
		// which of the two is the real one is a judgement, and the abandoned
		// one may be the only copy of something somebody wrote.
		findings = append(findings, Finding{
			Rule: "harness/region-duplicated", Severity: SeverityWarn, Subject: workspaceContract,
			Message: "more than one generated region; vat maintains the first and never looks at the rest, " +
				"which keep whatever they hold and are loaded as though it were generated",
			Fix: "delete the regions vat does not maintain, keeping anything of yours inside them",
		})
	case !harness.RegionMatches(string(content), region):
		findings = append(findings, Finding{
			Rule: "harness/workspace-drift", Severity: SeverityError, Subject: workspaceContract,
			Message: "the generated region no longer matches the manifest",
			Fix:     fixHarness, Fixable: true,
		})
	}
	if exists && len(content) > rootHarnessBudget {
		findings = append(findings, Finding{
			Rule: "harness/workspace-oversized", Severity: SeverityWarn, Subject: workspaceContract,
			Message: fmt.Sprintf("%d bytes; past roughly %d KiB a runtime may stop loading the per-repository contracts below it. Keep this file a map, not a copy",
				len(content), rootHarnessBudget/1024),
		})
	}

	for _, repo := range ws.Manifest.Repos {
		if repo.Archived || !fsx.IsDir(ws.RepoPath(repo)) {
			continue
		}
		path := filepath.Join(ws.RepoPath(repo), "AGENTS.md")
		repoContent, repoExists, err := fsx.ReadFileIfExists(path)
		if err != nil {
			return nil, err
		}
		repoRegion := harness.RenderRepo(ws.Manifest, repo)
		if !repoExists {
			findings = append(findings, Finding{
				Rule: "harness/repo-missing", Severity: SeverityWarn, Subject: repo.Name,
				Message: "has no AGENTS.md, so a session opened inside it sees no contract",
				Fix:     fixHarness, Fixable: true,
			})
			continue
		}
		if !harness.RegionMatches(string(repoContent), repoRegion) {
			findings = append(findings, Finding{
				Rule: "harness/repo-drift", Severity: SeverityWarn, Subject: repo.Name,
				Message: "the generated region no longer matches the manifest",
				Fix:     fixHarness, Fixable: true,
			})
		}
	}

	roles, malformedRoles, err := harness.LoadRoles(ws.Root)
	if err != nil {
		return nil, err
	}
	findings = append(findings, malformedDefinitions(malformedRoles)...)
	for _, role := range roles {
		if strings.TrimSpace(role.Description) == "" {
			findings = append(findings, Finding{
				Rule: "harness/role-metadata", Severity: SeverityWarn, Subject: role.Name,
				Message: "role has no description, so runtime adapters cannot advertise it",
			})
		}
		// A model name belongs to one vendor. Copying `model: opus` into a
		// Codex adapter produced a file naming a model Codex cannot resolve —
		// generated by the very tool whose job is to stop two runtimes from
		// drifting apart. No adapter names a model it cannot honour now, which
		// makes the role's declaration silently unused until it is split.
		findings = append(findings, unknownRuntimes(role.Name, "role", role.Runtimes, harness.RuntimeNames())...)
		if role.ModelIsAmbiguous() {
			findings = append(findings, Finding{
				Rule: "harness/model-ambiguous", Severity: SeverityWarn, Subject: role.Name,
				Message: fmt.Sprintf("one model for %s; a model name belongs to a single vendor, so no adapter can honour it",
					strings.Join(role.TargetedRuntimes(), " and ")),
				Fix: fmt.Sprintf("replace model: with a models: map, one entry per runtime, in %s/%s.md",
					harness.RolesDir, role.Name),
			})
		}
	}
	drifted, err := harness.AdapterDrift(ws.Root, roles)
	if err != nil {
		return nil, err
	}
	for _, path := range drifted {
		findings = append(findings, Finding{
			Rule: "harness/adapter-drift", Severity: SeverityWarn, Subject: path,
			Message: "runtime adapter no longer matches its role definition in " + harness.RolesDir,
			Fix:     fixHarness, Fixable: true,
		})
	}

	skills, malformedSkills, err := harness.LoadSkills(ws.Root)
	if err != nil {
		return nil, err
	}
	findings = append(findings, malformedDefinitions(malformedSkills)...)
	for _, skill := range skills {
		findings = append(findings, unknownRuntimes(skill.Name, "skill", skill.Runtimes, harness.SkillRuntimeNames())...)
		// A skill with no description is a skill no runtime can offer. It is
		// on disk, it is generated into every adapter, and it is invisible to
		// the agent that needed it.
		if strings.TrimSpace(skill.Description) == "" {
			findings = append(findings, Finding{
				Rule: "harness/skill-metadata", Severity: SeverityWarn, Subject: skill.Name,
				Message: "skill has no description, so no runtime can advertise it",
				Fix:     fmt.Sprintf("add description: to %s/%s/%s", harness.SkillsDir, skill.Dir, harness.SkillFile),
			})
		}
	}
	skillDrift, err := harness.SkillAdapterDrift(ws.Root, skills)
	if err != nil {
		return nil, err
	}
	for _, path := range skillDrift {
		findings = append(findings, Finding{
			Rule: "harness/adapter-drift", Severity: SeverityWarn, Subject: path,
			Message: "runtime adapter no longer matches its skill definition in " + harness.SkillsDir,
			Fix:     fixHarness, Fixable: true,
		})
	}

	// Deliberately not fixable. The repair is deleting a file, and vat does not
	// delete: the adapter may be the only remaining copy of a definition
	// somebody removed by accident, and a tool that tidies it away turns a
	// recoverable mistake into a silent one. The finding names the file.
	orphans, err := harness.OrphanedAdapters(ws.Root, roles, skills)
	if err != nil {
		return nil, err
	}
	for _, path := range orphans {
		findings = append(findings, Finding{
			Rule: "harness/adapter-orphaned", Severity: SeverityWarn, Subject: path,
			Message: "generated adapter for a definition that no longer exists; a session still " +
				"loads it and it points at a missing file",
			Fix: "restore the definition it was generated from, or delete " + path,
		})
	}
	return findings, nil
}

// malformedDefinitions reports a role or skill file that could not be read.
//
// Aborting the load instead meant one unparseable file withdrew the adapters of
// every other definition beside it, and reported only the first problem — so a
// second typo was invisible until the first was fixed.
func malformedDefinitions(malformed []harness.Malformed) []Finding {
	findings := make([]Finding, 0, len(malformed))
	for _, entry := range malformed {
		findings = append(findings, Finding{
			Rule: "harness/definition-malformed", Severity: SeverityError, Subject: entry.Path,
			Message: entry.Problem,
		})
	}
	return findings
}

// unknownRuntimes reports a runtime name no adapter is generated for.
//
// `runtimes:` decides which adapters exist, and a value that selects none —
// a typo for `claude`, or a runtime vat does not support yet — silently
// produces nothing. Nothing else notices: there is no adapter, so there is no
// drift; the metadata is present, so role-metadata passes; and a bare `model`
// binds to nothing, so model-ambiguous passes too. The definition sits on disk,
// inert, while every diagnostic reports the harness healthy.
//
// The supported list is a parameter because it is not the same for both kinds.
// Codex is a runtime vat generates a role adapter for and no skill adapter at
// all, so `runtimes: [codex]` is a correctly spelled name on a role and an
// inert definition on a skill. Checking skills against the role list is how
// that case went unreported: the rule documented as catching a value that
// generates no adapter was reading the wrong list to decide.
func unknownRuntimes(subject, kind string, declared, supported []string) []Finding {
	var findings []Finding
	for _, name := range declared {
		known := false
		for _, runtime := range supported {
			if strings.EqualFold(name, runtime) {
				known = true
				break
			}
		}
		if known {
			continue
		}
		findings = append(findings, Finding{
			Rule: "harness/runtime-unknown", Severity: SeverityWarn, Subject: subject,
			Message: fmt.Sprintf("declares runtime %q, which generates no %s adapter; it is one of %s or nothing at all",
				name, kind, strings.Join(supported, ", ")),
			Fix: "correct the runtimes: list, or drop it to target every runtime",
		})
	}
	return findings
}
