package cli

import (
	"context"
	"strings"

	"github.com/takealook97/vat/internal/harness"
	"github.com/takealook97/vat/internal/lint"
	"github.com/takealook97/vat/internal/ui"
	"github.com/takealook97/vat/internal/workspace"
)

func harnessAdoptCommand() *Command {
	return &Command{
		Name:    "adopt",
		Summary: "Bring hand-written agent files under the generated contract",
		Usage:   "vat harness adopt [--apply]",
		Long: `Move a runtime's hand-written agent files into .agents/ and generate the
adapters from them.

Anybody who would benefit from this already has agent files, written by hand
into one runtime's directory. This is the move that would otherwise be done by
copying, which is where adoption usually stops.

Reports what it would do and writes nothing until --apply. A file vat generated
is skipped, and so is one whose canonical definition already exists: that is
drift, which vat lint already reports, and the canonical copy is the one file
this tool will not overwrite.

Only the Markdown adapters are candidates. A Codex adapter keeps its prose
inside a TOML string, and turning that back into a body is a conversion with
judgement in it.`,
		Examples: []string{
			"vat harness adopt            # see what would move",
			"vat harness adopt --apply    # move it, then regenerate the adapters",
		},
		Run: runHarnessAdopt,
	}
}

func runHarnessAdopt(ctx context.Context, env *Env, args []string) error {
	set := newFlagSet("harness adopt")
	apply := set.Bool("apply", false, "write the definitions rather than reporting them")
	if err := parseFlags(set, args); err != nil {
		return err
	}
	ws, err := env.Workspace()
	if err != nil {
		return err
	}
	adoptions, err := harness.Adoptable(ws.Root)
	if err != nil {
		return err
	}

	// The work happens before anything is reported, so `--json` returns the
	// outcome as one document rather than a plan followed by loose status
	// lines. Every other command that writes on --apply reports it this way.
	var adopted map[string]bool
	var rendered []string
	if *apply {
		if adopted, rendered, err = applyAdoptions(ws, adoptions); err != nil {
			return err
		}
	}

	if env.JSON {
		return emitJSON(env, summariseAdoptions(adoptions, adopted))
	}

	adoptable := reportAdoptions(env, adoptions, adopted)
	if adoptable == 0 {
		env.Printer.Println("Nothing to adopt.")
		env.Printer.Hint("Every agent file here was generated by vat, or already has a definition.")
		return nil
	}
	if !*apply {
		env.Printer.Hint("\n%s to adopt. Re-run with --apply to write them.",
			pluralise(adoptable, "definition", "definitions"))
		return nil
	}
	for _, file := range rendered {
		env.Printer.Status(ui.LevelOK, file, "regenerated")
	}
	env.Printer.Hint("\nThe prose now lives in .agents/. Every adapter is generated from it.")
	return nil
}

// applyAdoptions writes the canonical definitions and regenerates every
// adapter, returning which adapters were adopted and what was rendered.
//
// The render goes through the path `vat harness render` uses, so an adopted
// definition's adapter is regenerated by the code that owns that decision
// rather than by a second copy of it here.
func applyAdoptions(ws *workspace.Workspace, adoptions []harness.Adoption) (map[string]bool, []string, error) {
	written, err := harness.Adopt(ws.Root, adoptions)
	if err != nil {
		return nil, nil, err
	}
	adopted := make(map[string]bool, len(written))
	for _, adoption := range written {
		adopted[adoption.Adapter] = true
	}
	rendered, err := lint.RenderHarness(ws)
	if err != nil {
		return nil, nil, err
	}
	return adopted, rendered, nil
}

// reportAdoptions names every candidate and returns how many can be adopted.
//
// Every refusal is reported, not the first: these commands run in a loop while
// somebody cleans a workspace up.
func reportAdoptions(env *Env, adoptions []harness.Adoption, adopted map[string]bool) int {
	var adoptable int
	for _, adoption := range adoptions {
		switch {
		case adoption.Refusal != "":
			env.Printer.Status(ui.LevelWarn, adoption.Adapter, "not adopted: "+adoption.Refusal)
		case adopted[adoption.Adapter]:
			adoptable++
			env.Printer.Status(ui.LevelOK, adoption.Canonical, "adopted from "+adoption.Adapter)
		default:
			adoptable++
			env.Printer.Status(ui.LevelInfo, adoption.Adapter, "would become "+adoption.Canonical)
		}
		// Said whether or not --apply was passed, so it is read before the move
		// rather than discovered after it. A key vat has no field for may still
		// be one the runtime honours.
		if len(adoption.Dropped) > 0 && adoption.Refusal == "" {
			env.Printer.Status(ui.LevelWarn, adoption.Adapter,
				"front matter not carried over: "+strings.Join(adoption.Dropped, ", "))
		}
	}
	return adoptable
}

func summariseAdoptions(adoptions []harness.Adoption, adopted map[string]bool) []adoptionSummary {
	listed := make([]adoptionSummary, 0, len(adoptions))
	for _, adoption := range adoptions {
		listed = append(listed, adoptionSummary{
			Adapter: adoption.Adapter, Canonical: adoption.Canonical,
			Kind: adoption.Kind, Name: adoption.Name,
			Refusal: adoption.Refusal, Dropped: adoption.Dropped,
			Adopted: adopted[adoption.Adapter],
		})
	}
	return listed
}

// adoptionSummary is the shape `vat harness adopt --json` reports.
type adoptionSummary struct {
	Adapter   string   `json:"adapter"`
	Canonical string   `json:"canonical,omitempty"`
	Kind      string   `json:"kind"`
	Name      string   `json:"name"`
	Refusal   string   `json:"refusal,omitempty"`
	Dropped   []string `json:"dropped,omitempty"`
	Adopted   bool     `json:"adopted"`
}
