package cli

import (
	"context"

	"github.com/takealook97/vat/internal/harness"
	"github.com/takealook97/vat/internal/lint"
	"github.com/takealook97/vat/internal/ui"
)

func harnessAdoptCommand() *Command {
	return &Command{
		Name:    "adopt",
		Summary: "Bring hand-written agent files under the generated contract",
		Usage:   "vat harness adopt [--apply]",
		Long: `Move a runtime's hand-written agent files into .agents/ and generate the
adapters from them.

Anybody who would benefit from this already has agent files, written by hand
into one runtime's directory. This is the move that would otherwise be done by
copying, which is where adoption usually stops.

Reports what it would do and writes nothing until --apply. A file vat generated
is skipped, and so is one whose canonical definition already exists: that is
drift, which vat lint already reports, and the canonical copy is the one file
this tool will not overwrite.

Only the Markdown adapters are candidates. A Codex adapter keeps its prose
inside a TOML string, and turning that back into a body is a conversion with
judgement in it.`,
		Examples: []string{
			"vat harness adopt            # see what would move",
			"vat harness adopt --apply    # move it, then regenerate the adapters",
		},
		Run: runHarnessAdopt,
	}
}

func runHarnessAdopt(ctx context.Context, env *Env, args []string) error {
	set := newFlagSet("harness adopt")
	apply := set.Bool("apply", false, "write the definitions rather than reporting them")
	if err := parseFlags(set, args); err != nil {
		return err
	}
	ws, err := env.Workspace()
	if err != nil {
		return err
	}
	adoptions, err := harness.Adoptable(ws.Root)
	if err != nil {
		return err
	}
	if env.JSON {
		listed := make([]adoptionSummary, 0, len(adoptions))
		for _, adoption := range adoptions {
			listed = append(listed, adoptionSummary{
				Adapter: adoption.Adapter, Canonical: adoption.Canonical,
				Kind: adoption.Kind, Name: adoption.Name, Refusal: adoption.Refusal,
			})
		}
		if err := emitJSON(env, listed); err != nil {
			return err
		}
		if !*apply {
			return nil
		}
	}

	// Reported before anything is written, and all at once. These commands run
	// in a loop while somebody cleans a workspace up.
	var adoptable int
	for _, adoption := range adoptions {
		if adoption.Refusal != "" {
			env.Printer.Status(ui.LevelWarn, adoption.Adapter, "not adopted: "+adoption.Refusal)
			continue
		}
		adoptable++
		if !*apply {
			env.Printer.Status(ui.LevelInfo, adoption.Adapter,
				"would become "+adoption.Canonical)
		}
	}
	if adoptable == 0 {
		if !env.JSON {
			env.Printer.Println("Nothing to adopt.")
			env.Printer.Hint("Every agent file here was generated by vat, or already has a definition.")
		}
		return nil
	}
	if !*apply {
		if !env.JSON {
			env.Printer.Hint("\n%s to adopt. Re-run with --apply to write them.",
				pluralise(adoptable, "definition", "definitions"))
		}
		return nil
	}

	written, err := harness.Adopt(ws.Root, adoptions)
	if err != nil {
		return err
	}
	for _, adoption := range written {
		env.Printer.Status(ui.LevelOK, adoption.Canonical, "adopted from "+adoption.Adapter)
	}
	// Rendered through the same path `vat harness render` uses, so an adopted
	// definition's adapter is regenerated as a pointer by the code that owns
	// that decision rather than by a second copy of it here.
	rendered, err := lint.RenderHarness(ws)
	if err != nil {
		return err
	}
	for _, file := range rendered {
		env.Printer.Status(ui.LevelOK, file, "regenerated")
	}
	env.Printer.Hint("\nThe prose now lives in .agents/. Every adapter is generated from it.")
	return nil
}

// adoptionSummary is the shape `vat harness adopt --json` reports.
type adoptionSummary struct {
	Adapter   string `json:"adapter"`
	Canonical string `json:"canonical,omitempty"`
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Refusal   string `json:"refusal,omitempty"`
}
