package brain

import (
	"encoding/json"
	"path/filepath"
	"sort"
	"strings"

	"github.com/takealook97/vat/internal/fsx"
)

// CurrentNotice is the line every generated CURRENT.md carries.
//
// It is provenance, not decoration. Without it the only question a build could
// ask about the file already on disk was whether its content matched what the
// records would render, and a file vat never wrote never matches — so adopting
// a knowledge repository that already kept an index of its own destroyed it.
const CurrentNotice = "<!-- Generated by `vat brain build` from the atomic records. Do not edit. -->"

// graphProvenance is the value the graph's `generated_by` field carries. The
// graph is JSON, so it cannot hold a comment; the field is the same claim.
const graphProvenance = "vat brain build"

// Unmanaged returns the projection files that exist but were not written by
// vat, sorted. They are the files a build must not touch.
//
// A file vat generated and somebody then edited is not one of these: it still
// carries the provenance, and it is drift, which `vat brain build` repairs.
// The two are reported apart because the repair for one is destruction of the
// other.
func Unmanaged(root string) ([]string, error) {
	var foreign []string
	for _, name := range Generated() {
		content, exists, err := fsx.ReadFileIfExists(filepath.Join(root, name))
		if err != nil {
			return nil, err
		}
		if !exists {
			continue
		}
		if !writtenByVat(name, content) {
			foreign = append(foreign, name)
		}
	}
	sort.Strings(foreign)
	return foreign, nil
}

// writtenByVat reports whether a projection's own content claims vat produced
// it. An empty file claims nothing and is treated as vat's to write: it is
// what a truncated write or an interrupted checkout leaves behind, and refusing
// to repair that would strand a repository over a file holding nothing.
func writtenByVat(name string, content []byte) bool {
	if len(strings.TrimSpace(string(content))) == 0 {
		return true
	}
	switch name {
	case CurrentFile:
		return strings.Contains(fsx.NormaliseNewlines(string(content)), CurrentNotice)
	case GraphFile:
		var header struct {
			Generated string `json:"generated_by"`
		}
		if err := json.Unmarshal(content, &header); err != nil {
			// Not JSON at all, so not this tool's graph. Whatever it is, it is
			// somebody's, and vat has no claim on the name.
			return false
		}
		return header.Generated == graphProvenance
	default:
		return false
	}
}
