package harness

import (
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Drift compares an adapter with the definition it was generated from. It
// cannot see the case where there is no definition left: delete
// .agents/roles/planner.md and the adapters stay, the runtime keeps advertising
// the role, and the session that opens it is told to read a file that is gone.
// Nothing reported that, because every adapter vat knew about still matched.

// GeneratedMarker is the sentence every adapter carries. It is exported so that
// the rule which finds abandoned adapters and the code that writes them cannot
// disagree about what marks a file as generated.
const GeneratedMarker = "Generated by `vat harness render`."

// AdapterRoots are the directories vat writes adapters into.
func AdapterRoots() []string {
	return []string{ClaudeAgentDir, ClaudeSkillDir, CodexAgentDir}
}

// OrphanedAdapters returns generated adapters that no definition would produce,
// relative to root and sorted.
//
// Only a file carrying GeneratedMarker is considered. An agent file somebody
// wrote by hand and never asked vat to manage is not vat's to report, and a rule
// that fires on a correct workspace is a rule that gets turned off.
func OrphanedAdapters(root string, roles []Role, skills []Skill) ([]string, error) {
	expected := map[string]bool{}
	for _, role := range roles {
		for _, adapter := range RenderAdapters(role) {
			expected[filepath.ToSlash(adapter.Path)] = true
		}
	}
	for _, skill := range skills {
		for _, adapter := range RenderSkillAdapters(skill) {
			expected[filepath.ToSlash(adapter.Path)] = true
		}
	}

	var orphans []string
	for _, dir := range AdapterRoots() {
		base := filepath.Join(root, dir)
		err := filepath.WalkDir(base, func(path string, entry fs.DirEntry, err error) error {
			if err != nil {
				// A directory vat has never written to is not a finding, and one
				// it cannot read is reported by the rules that read definitions
				// rather than silently turned into an orphan here.
				if os.IsNotExist(err) || os.IsPermission(err) {
					return nil
				}
				return err
			}
			if entry.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			slashed := filepath.ToSlash(rel)
			if expected[slashed] {
				return nil
			}
			marked, err := carriesMarker(path)
			if err != nil {
				return err
			}
			if marked {
				orphans = append(orphans, slashed)
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	sort.Strings(orphans)
	return orphans, nil
}

// markerWindow bounds how much of a file is read looking for the marker.
//
// A skill directory holds references and scripts beside its procedure, and this
// walk visits all of them on every lint. The marker is written into the first
// lines of a generated file by construction, so reading a whole 100MB asset to
// decide it is not one is work nobody asked for.
const markerWindow = 8 << 10

func carriesMarker(path string) (bool, error) {
	file, err := os.Open(path)
	if err != nil {
		if os.IsPermission(err) {
			return false, nil
		}
		return false, err
	}
	defer func() { _ = file.Close() }()

	window := make([]byte, markerWindow)
	read, err := io.ReadFull(file, window)
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		return false, err
	}
	return strings.Contains(string(window[:read]), GeneratedMarker), nil
}
