// Package harness generates and validates the agent contract files of a
// workspace: the workspace AGENTS.md, each repository's AGENTS.md, and the
// per-runtime adapters that point at one runtime-neutral role body.
//
// The design rule is the one the methodology applies to knowledge: a fact has
// exactly one owner, and everything else is a projection that can be
// regenerated and drift-checked. Here the manifest owns the repository roster
// and the trust boundary, `.agents/roles/*.md` owns each role's contract, and
// every AGENTS.md block and runtime adapter is generated from them.
package harness

import (
	"strings"

	"github.com/takealook97/vat/internal/fsx"
)

// Region markers delimit the part of a file vat owns. Everything outside them
// is hand-written and preserved untouched.
const (
	BeginMarker = "<!-- vat:begin generated -->"
	EndMarker   = "<!-- vat:end generated -->"
	// EditWarning sits immediately inside the region so a human editing the
	// file sees why their change would be overwritten.
	EditWarning = "<!-- Generated by `vat harness render` from vat.yaml. Do not edit inside this region. -->"
)

// ApplyRegion returns existing content with the generated region replaced. When
// no region is present the region is appended, preserving the hand-written
// content above it.
func ApplyRegion(existing, region string) string {
	block := BeginMarker + "\n" + EditWarning + "\n\n" + strings.TrimSpace(region) + "\n\n" + EndMarker
	beginAt := strings.Index(existing, BeginMarker)
	endAt := strings.Index(existing, EndMarker)
	if beginAt >= 0 && endAt > beginAt {
		return existing[:beginAt] + block + existing[endAt+len(EndMarker):]
	}
	trimmed := strings.TrimRight(existing, "\n")
	if trimmed == "" {
		return block + "\n"
	}
	return trimmed + "\n\n" + block + "\n"
}

// ExtractRegion returns the body between the markers, excluding the markers and
// the edit warning, and reports whether a region was found.
func ExtractRegion(content string) (string, bool) {
	beginAt := strings.Index(content, BeginMarker)
	endAt := strings.Index(content, EndMarker)
	if beginAt < 0 || endAt <= beginAt {
		return "", false
	}
	inner := content[beginAt+len(BeginMarker) : endAt]
	inner = strings.Replace(inner, EditWarning, "", 1)
	return strings.TrimSpace(inner), true
}

// RegionMatches reports whether a file's generated region already equals the
// freshly rendered one. It is the drift check `vat lint` runs.
func RegionMatches(content, region string) bool {
	found, ok := ExtractRegion(content)
	if !ok {
		return false
	}
	// Compared on content, not on the reader's git configuration. Under the
	// default core.autocrlf on Windows, a contract this tool wrote and committed
	// comes back with CRLF endings: comparing bytes reported drift on a file
	// nobody had touched, `vat lint --fix` rewrote it with LF, git converted it
	// back, and the finding returned on the next run for as long as anybody kept
	// looking. This repository pins its own tree in .gitattributes; a user's
	// workspace has no such file unless they write one.
	return fsx.NormaliseNewlines(found) == fsx.NormaliseNewlines(strings.TrimSpace(region))
}
